# Generated by Django 5.0.3 on 2024-03-24 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('nom_disparu', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=6)),
                ('telephone', models.IntegerField()),
                ('province', models.CharField(max_length=200)),
                ('lieu_disparition', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_disparition', models.DateField()),
                ('date_finded', models.DateField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('is_finded', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
