# Generated by Django 5.0.3 on 2024-03-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='date_finded',
            field=models.DateField(null=True),
        ),
    ]
