# Generated by Django 5.0.3 on 2024-03-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_alter_avis_date_finded'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='nombre_recherche',
            field=models.IntegerField(default=0),
        ),
    ]
