# Generated by Django 5.0.3 on 2024-04-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_remove_avis_nombre_recherche'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='photo',
            field=models.ImageField(default=1, upload_to='photo/'),
            preserve_default=False,
        ),
    ]
